libsdir <- Sys.getenv("R_LIBS_USER")
package_manager <- Sys.getenv("PACKAGE_MANAGER")
dir.create(libsdir, showWarnings = FALSE, recursive=TRUE) 
install.packages("devtools")
devtools::install(c('DBI', 'odbc', 'dotenv'), repos=package_manager, lib=libsdir)