libsdir <- Sys.getenv("R_LIBS_USER")
install.packages("remotes")
remotes::install_github("Enchufa2/rspm")
rspm::enable()
dir.create(libsdir, showWarnings = FALSE, recursive=TRUE) 
install.packages(c('DBI', 'odbc', 'dotenv'), lib=libsdir)